const departments = [
    ["Bond Specialty Insurance", [
    "BSI Actuary",
    "BSI BI&A",
    "BSI CEO and Direct Reports",
    "BSI Claim CMSUR",
    "BSI Claim CS",
    "BSI Claim FI",
    "BSI Claim Field",
    "BSI Claim PCL",
    "BSI Claim Pl",
    "BSI Claim PNP",
    "BSI Claim Shared",
    "BSI Comm'l Surety Express",
    "BSI Comm'l Surety Field",
    "BSI Comm'l Surety HO",
    "BSI Const. UK Surety",
    "BSI Construction Serv HO COGS",
    "BSI Construction Serv HO FBI",
    "BSI CS Express",
    "BSI CS Field",
    "BSI CS HO Core",
    "BSI CS HO Middle",
    "BSI CS HO Nat'l",
    "BSI CS HO Shared",
    "BSI Cyber/NCP",
    "BSI FI Field",
    "BSI FI Home Office",
    "BSI FI P&C",
    "BSI Field Management",
    "BSI Field RVPs",
    "BSI Finance",
    "BSI HR",
    "BSI INT'L SURETY",
    "BSI IT - App & Infra Support",
    "BSI IT - ATO & CoEs",
    "BSI IT - BI&A",
    "BSI IT - Claim",
    "BSI IT - Commercial Surety",
    "BSI IT - Construction",
    "BSI IT - Customer Journey",
    "BSI IT - Management & APMO",
    "BSI IT - Management Liability",
    "BSI IT - Tech Ops Services",
    "BSI IT Core Salesforce",
    "BSI IT-Common Domains&Services",
    "BSI Legal",
    "BSI Marketing",
    "BSI ML International",
    "BSI ML Programs",
    "BSI ML Strategic Initiatives",
    "BSI ML Undw & Stgc Mngmt",
    "BSI Operations",
    "BSI Operations BPO",
    "BSI Ops FI P&C",
    "BSI P&C Lg Acct",
    "BSI PCL Field",
    "BSI PCL Home Office",
    "BSI PL Accts & Lwyrs",
    "BSI PL Field-A & E",
    "BSI PL Field-Real Estate Agent",
    "BSI PL Home Office",
    "BSI Private Non-Profit Field",
    "BSI Private Non-Profit HO",
    "BSI Product Solutions",
    "BSI Professional Liability MPL",
    "BSI Regulatory",
    "BSI Research and Development",
    "BSI Strategic Pln & Exec",
    "BSI TCI Global",
    "BSI TCI Global CMSUR",
    "BSI TCI Global CS",
    "BSI Training",
    "Private Non-Profit CUF"]],

    ["Business Insurance", ["Ag Central Denver",
    "Ag East",
    "Ag West Fresno",
    "Ag West Northwest",
    "Ag West Rancho Cordova",
    "Agribusiness Executive",
    "Agribusiness MGA",
    "Agribusiness TASC",
    "Architects and Engineers",
    "BC_UW_Tech_Tampa",
    "BI - Innovation & Insights",
    "BI Analytics & Research",
    "BI BCO-Leadership",
    "BI BCO-Strategy",
    "BI Field VPs",
    "BI IMA Data Delivery",
    "BI IMA Data Modernization",
    "BI Product Auto",
    "BI Product Comm Packaging",
    "BI Product Compliance",
    "BI Product Dev & Innovation",
    "BI Product GL & UMB",
    "BI Product IM",
    "BI Product Property",
    "BI Product WC",
    "BI Shared UW Casualty",
    "BI Shared UW FLR",
    "BI Shared UW TCI",
    "BI Shrd Actuarial Enterprise",
    "BI Shrd Actuarial Loss",
    "BI Shrd Actuarial Product",
    "BI Shrd Actuarial Regulatory",
    "BI Shrd Executive Direct Rpts",
    "BI Shrd Finance Controller",
    "BI Shrd Finance FP&A",
    "BI Shrd General Counsel",
    "BI Shrd HR Home Office Leads",
    "BI Shrd HR Sales Training",
    "BI Shrd HR UW Training",
    "BI Shrd UW Property",
    "BI SPE Worldwide",
    "BI SPE-Shared Services",
    "BI VS - Product Operations",
    "BI VS-Journey-Agency Lifecycle",
    "BI VS-Journey-Post Bind",
    "BI VS-Journey-Prospect Thru UW",
    "BI VS-Product-Cross Product",
    "BI VS-Product-Line",
    "BII Finance BI&A",
    "BM Administration",
    "BM Central",
    "BM Executive",
    "BM Express",
    "BM Great Lakes",
    "BM Metro",
    "BM Mid Atlantic",
    "BM Multi Region",
    "BM Multi Region Mgmt",
    "BM Northeast",
    "BM Pacific",
    "BM South Central",
    "BM Southern",
    "BM Upper Midwest",
    "Boiler Re Treaty",
    "Bus Center IM PAK Conversion",
    "Bus Center UW CA Atlanta",
    "Bus Center UW CA Denver",
    "Bus Center UW CA Hartford",
    "Bus Center UW CA St Paul",
    "Bus Center UW Const Atlanta",
    "Bus Center UW Const Denver",
    "Bus Center UW Const Hartford",
    "Bus Center UW Const St Paul",
    "Bus Center UW Core/Red Flag",
    "Bus Center UW Excess Atlanta",
    "Bus Center UW Excess Denver",
    "Bus Center UW Excess Hartford",
    "Bus Center UW Express NB",
    "Bus Center UW IM Atlanta",
    "Bus Center UW IM Denver",
    "Bus Center UW IM Hartford",
    "Bus Center UW IM St Paul",
    "Bus Center UW MM Mgmt",
    "Bus Center UW OG Denver",
    "Bus Center UW Selct Management",
    "Bus Center UW Tech St Paul",
    "Bus Process Effectiveness",
    "CA Central 1",
    "CA Central 2",
    "CA Central Mgmt",
    "CA Great Lakes",
    "CA Great Lakes Mgmt",
    "CA Metro",
    "CA Metro Mgmt",
    "CA Mid Atlantic 1",
    "CA Mid Atlantic 2",
    "CA Mid Atlantic 3",
    "CA Mid Atlantic Mgmt",
    "CA Mtn West",
    "CA Mtn West Mgmt",
    "CA Multi Region Mgmt",
    "CA Northeast",
    "CA Northeast Mgmt",
    "CA Pacific N",
    "CA Pacific N Mgmt",
    "CA Pacific S 1",
    "CA Pacific S 2",
    "CA Pacific S 3",
    "CA Pacific S Mgmt",
    "CA South Central 1",
    "CA South Central 2",
    "CA South Central Mgmt",
    "CA Southern 1",
    "CA Southern 2",
    "CA Southern Mgmt",
    "CA Upper Midwest",
    "CA Upper Midwest Mgmt",
    "CAG IndustryEdge",
    "Canada Crossborder IMA",
    "CNS Central",
    "CNS Central Mgmt",
    "CNS Cure UW Stds",
    "CNS Environmental",
    "CNS Executive",
    "CNS Great Lakes",
    "CNS Great Lakes Mgmt",
    "CNS Metro",
    "CNS Metro Mgmt",
    "CNS Mid Atlantic",
    "CNS Mid Atlantic Mgmt",
    "CNS Mtn West",
    "CNS Mtn West Mgmt",
    "CNS Northeast",
    "CNS Northeast Mgmt",
    "CNS Pacific 1",
    "CNS Pacific 2",
    "CNS Pacific Mgmt",
    "CNS Renewable Energy",
    "CNS South Central",
    "CNS South Central Mgmt",
    "CNS Southern",
    "CNS Southern Mgmt",
    "CNS Upper Midwest",
    "CNS Upper Midwest Mgmt",
    "Commercial Executive",
    "EC Central",
    "EC Central Mgmt",
    "EC Executive",
    "EC Great Lakes",
    "EC Great Lakes Mgmt",
    "EC Metro",
    "EC Metro Mgmt",
    "EC Mid Atlantic",
    "EC Mtn West",
    "EC Mtn West Mgmt",
    "EC Multi Region Mgmt",
    "EC Northeast",
    "EC Northeast Mgmt",
    "EC Pacific N",
    "EC Pacific N Mgmt",
    "EC Pacific S",
    "EC South Central",
    "EC South Central Mgmt",
    "EC Southern",
    "EC Southern Mgmt",
    "EC Upper Midwest",
    "EC Upper Midwest Mgmt",
    "Field Mgt Executive",
    "Field Mgt Field Management",
    "IM Central",
    "IM Central Mgmt",
    "IM Executive",
    "IM Great Lakes",
    "IM Great Lakes Mgmt",
    "IM Metro",
    "IM Metro Mgmt",
    "IM Mid Atlantic",
    "IM Mtn West",
    "IM Mtn West Mgmt",
    "IM Multi Region Mgmt",
    "IM Northeast",
    "IM Pacific",
    "IM Pacific Mgmt",
    "IM South Central",
    "IM South Central Mgmt",
    "IM Southern",
    "IM Upper Midwest",
    "IM Upper Midwest Mgmt",
    "LS CIP Project",
    "M Atlantic NP Mgmt",
    "MM Act Mbu1",
    "MM Act Mbu2",
    "MM Shared Finance",
    "National Actuarial",
    "National Central Admin Mktg",
    "National Central Marketing",
    "National Finance",
    "National Finance Unbundled",
    "National Financial Integrity",
    "National Mktg Administration",
    "National North Field Marketing",
    "National Northeast Admin Mktg",
    "National Northeast Marketing",
    "National Product Development",
    "National South Admin Marketing",
    "National South Marketing",
    "National West Admin Marketing",
    "National West Marketing",
    "Natl Credit Risk Management",
    "Natl North Field Admin Mktg",
    "Natl Specialty Group Captives",
    "NI_Agency Automation",
    "Northfield Binding Eastern Rgn",
    "Northfield Binding Western Rgn",
    "Northfield Solutions UW",
    "Northfield Specialty Admin",
    "NP Central",
    "NP Central Mgmt",
    "NP Excess",
    "NP Excess Mgmt",
    "NP Executive",
    "NP Great Lakes",
    "NP Great Lakes Mgmt",
    "NP Metro",
    "NP Metro Mgmt",
    "NP Mid Atlantic",
    "NP Mtn West",
    "NP Multi Region",
    "NP Multi Region Mgmt",
    "NP Northeast",
    "NP Northeast Mgmt",
    "NP Pacific",
    "NP Pacific Mgmt",
    "NP South Central",
    "NP Southern",
    "NP Southern Mgmt",
    "NP Upper Midwest",
    "NP Upper Midwest Mgmt",
    "OCR RRP",
    "OG Executive",
    "OG Great Lakes",
    "OG Great Lakes Mgmt",
    "OG Mtn West",
    "OG Mtn West Mgmt",
    "OG Multi Region Mgmt",
    "OG South Central",
    "OG South Central Mgmt",
    "OG UW Services",
    "OM Central",
    "OM Central Mgmt",
    "OM Executive",
    "OM Great Lakes",
    "OM Metro",
    "OM Metro Mgmt",
    "OM Mid Atlantic",
    "OM Mtn West",
    "OM Multi Region Mgmt",
    "OM Northeast",
    "OM Northeast Mgmt",
    "OM Pacific",
    "OM Pacific Mgmt",
    "OM South Central",
    "OM Southern",
    "OM Virtual BC",
    "OM Yachts",
    "Operations Finance Support",
    "PSS Central Sales",
    "PSS Executive",
    "PSS Great Lakes Sales",
    "PSS Loss Sensitive",
    "PSS Mid Atlantic Sales",
    "PSS Mtn West Sales",
    "PSS Multi Region 1",
    "PSS Multi Region 2",
    "PSS Multi Region 3",
    "PSS Multi Region Mgmt",
    "PSS Northeast Sales",
    "PSS Southern Mgmt",
    "PSS Southern Sales",
    "PSS Upper Midwest Sales",
    "Rmd Admin and Compliance",
    "RMD Business Solutions",
    "RMD Pool Accounting",
    "RMD SIU and Collections",
    "RMIS - Administration",
    "RMIS IAC Middle Market",
    "RMIS IAC National Accounts",
    "RMIS Operations Support",
    "SB OIE Default",
    "SB UK Management",
    "SB US Management",
    "SB US OIE Default",
    "SB US Pricing & Ops",
    "SC - Bus Process Effectiveness",
    "SC Business Analytics",
    "SC UW & Product",
    "Select - Product Management",
    "Select Atlanta UW",
    "Select Braintree UW",
    "Select Central Mgmt",
    "Select Central Sales",
    "Select Charlotte UW",
    "Select Chicago Inside Sales",
    "Select Dallas UW",
    "Select Denver UW",
    "Select Diamond Bar UW",
    "Select Great Lakes Mgmt",
    "Select Great Lakes Sales",
    "Select Hartford UW",
    "Select Hunt Valley UW",
    "Select Kansas City UW",
    "Select Metro Mgmt",
    "Select Metro Sales",
    "Select Metro UW",
    "Select Mid Atlantic Mgmt",
    "Select Mid Atlantic Sales",
    "Select Midwest Management",
    "Select Midwest Renewal UW",
    "Select Mtn West Mgmt",
    "Select Mtn West Sales",
    "Select Multi Region Mgmt",
    "Select Multi Region Sales",
    "Select Naperville UW",
    "Select National Dist UW",
    "Select North East Management",
    "Select North East Renewal UW",
    "Select Northeast Mgmt",
    "Select Northeast Sales",
    "Select Pacific Management",
    "Select Pacific Mgmt",
    "Select Pacific Renewal",
    "Select Pacific Sales",
    "Select Richardson Inside Sales",
    "Select Sales Operations",
    "Select South Central Mgmt",
    "Select South Central Sales",
    "Select Southern Management",
    "Select Southern Mgmt",
    "Select Southern Renewal UW",
    "Select Southern Sales",
    "Select Spokane Inside Sales",
    "Select Underwriting",
    "Select Upper Midwest Sales",
    "Select Walnut Creek UW",
    "Select-Agency Automation Execs",
    "Select-Natl Dist Natl Practice",
    "Small Commercial Actuarial",
    "Small Commercial Execution",
    "Small Commercial Finance",
    "Southern IM Mgmt",
    "Tech Central",
    "Tech Central Mgmt",
    "Tech Central Sales",
    "Tech CUO Segment Leads",
    "Tech Executive",
    "Tech Great Lakes",
    "Tech Great Lakes Mgmt",
    "Tech Great Lakes Sales",
    "Tech Loss Sensitive",
    "Tech Metro",
    "Tech Metro Mgmt",
    "Tech Metro Sales",
    "Tech Mid Atlantic",
    "Tech Mid Atlantic Mgmt",
    "Tech Mtn West",
    "Tech Mtn West Sales",
    "Tech Multi Region Mgmt",
    "Tech Northeast",
    "Tech Northeast Mgmt",
    "Tech Northeast Sales",
    "Tech Pacific N",
    "Tech Pacific N Mgmt",
    "Tech Pacific S",
    "Tech Pacific S Sales",
    "Tech South Central",
    "Tech South Central Mgmt",
    "Tech South Central Sales",
    "Tech Southern",
    "Tech Southern Sales",
    "Tech Upper Midwest",
    "Tech Upper Midwest Mgmt",
    "Tech Upper Midwest Sales",
    "Transporation Western Region",
    "Transportation Eastern Region",
    "Transportation UW and Admin"]],

    ["Corporate Claim", ["Albany Syracuse Cl",
    "Albany Syracuse WC",
    "Albuquerque WC",
    "Alpharetta Cl",
    "Alpharetta WC",
    "Analytics Value Stream",
    "Auto Business Analytics",
    "Auto Fld Trainers",
    "Auto Heavy Equip",
    "Auto Prod Development AB",
    "Auto Prod Development AD",
    "Auto Prod Supp",
    "B & M - Claim",
    "Baltimore Cl",
    "Baltimore WC",
    "Baton Rouge Cl",
    "Baton Rouge WC",
    "Behavioral Science",
    "BI Ga'S",
    "BI Oth-Assumed Re Client Srvs",
    "BI Other - Assumed Re Claims",
    "BI Other-Finance",
    "BI WC",
    "BIrmingham Cl",
    "BIrmingham WC",
    "Blue Bell Cl",
    "Blue Bell Pl",
    "Blue Bell WC",
    "Boat Yacht Claims",
    "Boston Cl",
    "Boston WC",
    "BRC - WC MED BILL",
    "BRC Operations",
    "Brookfield Cl",
    "Brookfield WC",
    "Buffalo Rochester Cl",
    "Buffalo-Rochester WC",
    "Business Torts",
    "Cae'S",
    "Cat",
    "CBIA Clm Info Strat & Analysis",
    "CBIA Clm Str Deliv Serv & Geo",
    "CBIA Data & Research",
    "CBIA Executive",
    "CBP Operations",
    "CBPG Property Damage",
    "CBPG Product",
    "CCS WKFC MGMT & Analytics",
    "Chantilly Cl",
    "Chantilly WC",
    "Charleston WC",
    "Chicago Liability Cl",
    "Chicago WC",
    "Cincinnati CL",
    "Claim Accounting Serv Grp",
    "Claim Center General Counsel",
    "Claim CX",
    "Claim Legal & BSci Product",
    "Claim Legal Auto",
    "Claim Legal Fraud",
    "Claim Legal Ho",
    "Claim Legal Liability",
    "Claim Legal Property",
    "Claim Legal SRG",
    "Claim Legal Workers Comp",
    "Claim Shared Services BI&A",
    "Claim Shared Services Ops",
    "Claim U Auto Pd",
    "Claim U Liability",
    "Claim U Property",
    "Claim U Work Comp",
    "Claim Workforce Effectiveness",
    "Claim/CSS Correspondence",
    "Cleveland Cl",
    "Clm Agile Ofc & Mgmt Ops",
    "Clm Bus Deliv Office",
    "Clm Rptg - Quality Assurance",
    "Clm Rptg - Training",
    "Clm Strategic Comms",
    "Complex Case",
    "Connecticut",
    "Connecticut Apprs",
    "Connecticut Auto Exp",
    "Connecticut BI Auto BI",
    "Connecticut BI Liab",
    "Connecticut Blended AD",
    "Connecticut Gl Nurse",
    "Connecticut Liab",
    "Connecticut Line Leads",
    "Connecticut Mgmt/Supp",
    "Connecticut PI Bi-No Fault",
    "Connecticut PI Liab",
    "Connecticut PI Prop",
    "Connecticut Prop Pl",
    "Connecticut TCX",
    "Connecticut TMMS",
    "Connecticut Wcomp",
    "Const Large Loss Mgmt",
    "Construction - Central",
    "Construction - Central CD",
    "Construction - Northeast",
    "Construction - Northeastern CD",
    "Construction - Southeast",
    "Construction - Southern CD",
    "Construction - Southwest CD",
    "Construction Wcomp",
    "Construction - Western CD",
    "Construction- Southwest",
    "Construction- Western",
    "Core Claim Enhancements",
    "Cov In Place Unit",
    "CU Cross Lines",
    "CU Learn Strat",
    "CU Management",
    "CU Ops & Logistics",
    "CU Specialty",
    "Customer Care - Buffalo",
    "Customer Care - Home Office",
    "Customer Care - Houston",
    "Customer Care - Orlando",
    "Customer Care-Ho Lamberton Rd",
    "Customer Value Stream",
    "Dallas Cl",
    "Dallas WC",
    "Denver Cl",
    "Denver WC",
    "Des Moines Cl",
    "Des Moines WC",
    "Diamond Bar Liability Cl",
    "Diamond Bar WC",
    "Employee Value Stream",
    "Enterprise MCU",
    "Environmental Coverage Unit",
    "Field & Financial Services",
    "Field Ops East",
    "Field Ops West Midwest",
    "Field Region Admin",
    "Finance",
    "Finance & Mis",
    "Florida",
    "Florida Appraisers",
    "Florida Apprs",
    "Florida Auto Express",
    "Florida Auto Glass Unit",
    "Florida BI Auto BI",
    "Florida BI GL",
    "Florida BI Liab",
    "Florida Blended AD",
    "Florida CL Abi",
    "Florida Gl Nurse",
    "Florida Liab PL",
    "Florida Line Leads",
    "Florida Mgmt Sppt",
    "Florida NF Lit Arb",
    "Florida NF Lit ARB",
    "Florida NF PL",
    "Florida Nurses-WC",
    "Florida PL Liab",
    "Florida PL No-Flt",
    "Florida TMMS",
    "Florida Wcomp",
    "FOSS",
    "Fresno CA-WC",
    "Ft Lauderdale Cl",
    "Ft Lauderdale WC",
    "GL Analytics",
    "GL Product",
    "H.O. Env Clm Unit",
    "Hartford Cl",
    "Hartford WC",
    "HO Claim Handling / Oversight",
    "Houston Cl",
    "Houston Nurses",
    "Houston WC",
    "Indianapolis CL",
    "Indianapolis WC",
    "In-House Coverage Litigation",
    "Inland Marine Claim",
    "ISD Core Operations",
    "Jackson MS CL",
    "Jackson MS WC",
    "Jacksonville,FL CL",
    "Jacksonville,FL WC",
    "Knoxville Cl",
    "Knoxville WC",
    "Lake Michigan",
    "Lake Michigan Apprs",
    "Lake Michigan BI Auto BI",
    "Lake Michigan BI Liab",
    "Lake Michigan BI Prop",
    "Lake Michigan Blended AD",
    "Lake Michigan CL Auto BI",
    "Lake Michigan GL Nurse",
    "Lake Michigan Line Leads",
    "Lake Michigan Mgmt",
    "Lake Michigan No Fault",
    "Lake Michigan Nurse-WC",
    "Lake Michigan PI Liab",
    "Lake Michigan PI Prop",
    "Lake Michigan Subro Prop",
    "Lake Michigan TMMS",
    "Lake Michigan WC",
    "Las Vegas Cl",
    "Las Vegas WC",
    "Latent Injury Oversight",
    "Legal Resource Management",
    "Mandeville Cl",
    "Marlton CL",
    "Marlton WC",
    "Mcu - Subro",
    "Memphis Cl",
    "Memphis WC",
    "Merrilville Cl",
    "Merrilville WC",
    "Metairie Cl",
    "Metairie WC",
    "Metro NY-NJ ABI Nurse",
    "Metro NY-NJ Appraisers",
    "Metro NY-NJ BI Auto BI",
    "Metro NY-NJ BI Liab",
    "Metro NY-NJ BI Prop",
    "Metro NY-NJ Blended AD",
    "Metro NY-NJ Gl Nurse",
    "Metro NY-NJ Line Leads",
    "Metro NY-NJ Mgmt/Supp",
    "Metro NY-NJ Nf Lit Arb",
    "Metro NY-NJ PI Liab",
    "Metro NY-NJ PI No-Fault",
    "Metro NY-NJ PI Prop",
    "Metro NY-NJ TMMS",
    "Metro NY-NJ WC",
    "Miami Cl",
    "Miami WC",
    "Mid-Atlantic",
    "Mid-Atlantic ABI Nurse",
    "Mid-Atlantic Appr",
    "Mid-Atlantic BI ABI",
    "Mid-Atlantic BI GL",
    "Mid-Atlantic BI Prop",
    "Mid-Atlantic Blended AD",
    "Mid-Atlantic GL Nurse",
    "Mid-Atlantic Mgmt",
    "Mid-Atlantic No Fault",
    "Mid-Atlantic Ops",
    "Mid-Atlantic PI ABI",
    "Mid-Atlantic PI Prop",
    "Mid-Atlantic Prop Pl",
    "Mid-Atlantic Subro WC",
    "Mid-Atlantic WC",
    "Mid-Atlantic WC Nurse",
    "Mid-Atlantic WC TCX",
    "Morris Plains Liability Cl",
    "Morris Plains WC",
    "Mountain West Auto Express",
    "Mountain West Hub Blend",
    "Mtn West",
    "Mtn West Ad TI BI",
    "Mtn West Ad Tl BI",
    "Mtn West Ad Tl PI",
    "Mtn West Appr Dis",
    "Mtn West Apprs",
    "Mtn West BI Auto BI",
    "Mtn West BI Liab",
    "Mtn West BI Prop",
    "Mtn West Blended AD",
    "Mtn West Gl Nurse",
    "Mtn West Line Leads",
    "Mtn West Mgmt Sppt",
    "Mtn West Mgmt/Supp",
    "Mtn West PI",
    "Mtn West PI Liab",
    "Mtn West PI Prop",
    "Mtn West TMMS",
    "Mtn West WC TCX",
    "Mtn West Wcomp",
    "Nashville Cl",
    "Nashville WC",
    "NAUC General Liabilty",
    "NAUC WC",
    "New England",
    "New England Appr",
    "New England BI ABI",
    "New England BI Prop",
    "New England Blended AD",
    "New England HOPD",
    "New England Mgmt",
    "New England NF LIT ARB",
    "New England No Fault",
    "New England Ops",
    "New England PI ABI",
    "New England PI Prop",
    "New England WC",
    "New England WC Nurse",
    "New York City Liab CL",
    "New York Liability Cl",
    "New York WC",
    "Newark CL",
    "Newark WC",
    "NI - Cargo Claims",
    "Ni - Phys Damage_Cargo Claim",
    "Ni - Specialty Lines Claims",
    "Ni - Support_Ops",
    "Ni - Transportation Liab Claim",
    "Nor Cal-Nevada Appr",
    "Nor Cal-Nevada BI ABI",
    "Nor Cal-Nevada BI GL",
    "Nor Cal-Nevada BI Prop",
    "Nor Cal-Nevada Blended AD",
    "Nor Cal-Nevada GL Nurse",
    "Nor Cal-Nevada Mgmt",
    "Nor Cal-Nevada No Fault",
    "Nor Cal-Nevada Ops",
    "Nor Cal-Nevada PI ABI",
    "Nor Cal-Nevada PI Prop",
    "Nor Cal-Nevada WC",
    "Nor Cal-Nevada WC Nurse",
    "North Haven Cl",
    "North Haven WC",
    "North Texas -OK",
    "North Texas -OK Apprs",
    "North Texas -OK BI Auto BI",
    "North Texas -OK BI Prop",
    "North Texas -OK Blended AD",
    "North Texas -OK GL Nurse",
    "North Texas -OK Line Leads",
    "North Texas -OK NF",
    "North Texas -OK Prop PL",
    "North Texas -OK WC",
    "North Texas -OK WC Nurse",
    "North Texas -OK WC TCX",
    "NorthTexas -OK Other",
    "Oklahoma City CL",
    "Oklahoma City WC",
    "Orlando Cl",
    "Orlando WC",
    "Overland Park Cl",
    "Overland Park WC",
    "PC Clm - Subro Rpd",
    "PC Clm Admin - Exec",
    "PC Clm H/R Ho",
    "PC Clm Property Field Trainers",
    "PC Cl, Clm Reg, Structures",
    "PC Clm, Construct Nurses-100%",
    "PC Clm, Construction Mgmt",
    "PC Clm, Construction Nurses",
    "PC Clm, Ho Wc TMMS",
    "PC Clm, Mgmt Ref Stretch",
    "PC Cl, National Prop Managers",
    "PC Clm, Subro - Admin 2003",
    "PC Clm, Wc Mrt Group",
    "Philadelphia Cl",
    "Philadelphia WC",
    "Phoenix Cl",
    "Phoenix WC",
    "PI Ga'S",
    "PI Self Svs",
    "PIttsburgh Cl",
    "PIttsburgh WC",
    "Portland CL",
    "Portland WC",
    "Production Support",
    "Property Lit & Coverage Suppt",
    "Property MI",
    "Property Ops",
    "Property Product Development",
    "Providence Cl",
    "Providence WC",
    "QM Auto",
    "Qm Liab",
    "Qm Prop",
    "Qm Wcomp",
    "Rancho Cordova Cl",
    "Rancho Cordova WC",
    "Reg Compliance",
    "Reinsurance Litigation",
    "Richmond Cl",
    "Richmond WC",
    "Salt Lake City CL",
    "San Antonio CL",
    "San Antonio WC",
    "Scranton Cl",
    "Scranton WC",
    "Seattle CL",
    "Shared Strategic Resource",
    "South Texas Auto Express",
    "South Texas BI ABI",
    "South Texas BI Prop",
    "South Texas Blended AD",
    "South Texas Hub Blend",
    "South Texas Mgmt",
    "South Texas No Fault",
    "South Texas Ops",
    "South Texas PI ABI",
    "South Texas PI Prop",
    "South Texas WC",
    "South Texas WC Nurse",
    "Southern",
    "Southern Appr",
    "Southern BI ABI",
    "Southern BI GL",
    "Southern BI Prop",
    "Southern Blended AD",
    "Southern CA",
    "Southern CA BI GL",
    "Southern CA BI Prop",
    "Southern CA GL Nurse",
    "Southern CA Mgmt",
    "Southern CA Ops",
    "Southern CA PI Prop",
    "Southern CA WC",
    "Southern CA WC Nurse",
    "Southern Cal WC",
    "Southern California WC",
    "Southern GL Nurse",
    "Southern Mgmt",
    "Southern No Fault",
    "Southern Ops",
    "Southern PI ABI",
    "Southern PI Prop",
    "Southern WC",
    "Southern WC Nurse",
    "SPC Claim, Ocean Marine",
    "SPC Claim, Spec Oil and Gas",
    "Specialty TPA Mgmt",
    "Springfield Cl",
    "Springfield WC",
    "SRG Engineering",
    "SRG Hartford Operations",
    "SRG Investigators",
    "SRG Products Unit",
    "St Louis Cl",
    "St Louis WC",
    "St Paul Liability Cl",
    "St Paul WC",
    "Staff Counsel BRC",
    "Staff Counsel BRC 2",
    "Staff Counsel First Party",
    "Staff Counsel Ho",
    "SUBRO NEW ENGLAND ARB",
    "Subro New England Auto",
    "Tampa Kennedy Cl",
    "Tampa Kennedy WC",
    "Technology Value Stream",
    "Tenn-Ohio Valley",
    "Tenn-Ohio Valley Adv Subro",
    "Tenn-Ohio Valley Appr",
    "Tenn-Ohio Valley BI ABI",
    "Tenn-Ohio Valley BI Prop",
    "Tenn-Ohio Valley Blended AD",
    "Tenn-Ohio Valley Mgmt",
    "Tenn-Ohio Valley No Fault",
    "Tenn-Ohio Valley Ops",
    "Tenn-Ohio Valley PI ABI",
    "Tenn-Ohio Valley PI Liab",
    "Tenn-Ohio Valley PI Prop",
    "Tenn-Ohio Valley WC",
    "Tenn-Ohio Valley WC Nurse",
    "TIS FIRE TEAM",
    "TIS FLD OPS 07",
    "TIS FLD OPS 09",
    "TIS HOME OFFICE",
    "TIS NATIONAL MED",
    "TIS Prosecution",
    "TIS Resource Unit",
    "TIS SPEC INV GRP",
    "TIS STAFF COUNSEL",
    "Troy CL",
    "Troy WC",
    "Upper Midwest",
    "Upper Midwest Appr",
    "Upper Midwest BI ABI",
    "Upper Midwest BI GL",
    "Upper Midwest BI Prop",
    "Upper Midwest Blended AD",
    "Upper Midwest GL Nurse",
    "Upper Midwest Mgmt",
    "Upper Midwest No Fault",
    "Upper Midwest Ops",
    "Upper Midwest PI ABI",
    "Upper Midwest PI Prop",
    "Upper Midwest WC",
    "Upper Midwest WC Nurse",
    "Upper Midwest WC TCX St Paul",
    "Upstate New York Blended AD",
    "Upstate NY ABI Nurse",
    "Upstate NY Appr",
    "Upstate NY Appr Disp",
    "Upstate NY Auto Express",
    "Upstate NY BI ABI",
    "Upstate NY BI AD Tl",
    "Upstate NY BI Prop",
    "Upstate NY Hub Blend",
    "Upstate NY Mgmt",
    "Upstate NY Nf Lit",
    "Upstate NY No Fault",
    "Upstate NY Ops",
    "Upstate NY PI ABI",
    "Upstate NY PI AD Tl",
    "Upstate NY PI Prop",
    "Upstate NY WC",
    "Upstate NY WC Nurse",
    "Upstate NY WC Nurse Mrt",
    "User Experience",
    "Virgina Carolin Line Leads",
    "Virgina Carolina Ad Tl BI",
    "Virgina Carolina Mgmt/Supp",
    "Virginia Carolina Abi-Nf",
    "Virginia Carolina Ad Tl PI",
    "Virginia Carolina Apprs",
    "Virginia Carolina BI Auto BI",
    "Virginia Carolina BI Liab",
    "Virginia Carolina BI Prop",
    "Virginia Carolina Blended AD",
    "Virginia Carolina Gl Nurse",
    "Virginia Carolina PI Liab",
    "Virginia Carolina PI Prop",
    "Virginia Carolina Prop CI",
    "Virginia Carolina Prop PI",
    "Virginia Carolina TMMS",
    "Virginia Carolina WC",
    "Walnut Creek Liability CL",
    "Walnut Creek WC",
    "Wc Large Loss",
    "WC Product Development Group",
    "Wcomp",
    "White Plains Liability Cl"]],

    ["Corporate Staff", ["1099/Escheatment",
    "Accounting Operations",
    "Accounting Policy",
    "Admin Services Admin",
    "Advertising and Branding",
    "Agency Compensation",
    "Aircraft Operations",
    "Asset Management",
    "Banking Operations",
    "BI Shared Marketing",
    "Bldg Op-Admin",
    "Building Maintenance",
    "Building Op - 99 Lamberton Rd",
    "Canada CB CAT Strategy",
    "Cash Management",
    "Catastrophe Strategy/Analysis",
    "Ceded Re Operations",
    "Central Mail",
    "Choral Club",
    "Chq-Employee Benefits",
    "Claim Field Human Resourcesv",
    "College Relations",
    "Communications",
    "Community Relations",
    "Compensation",
    "CORP AUDIT CAD",
    "Corp Cont-Disburse Proces",
    "CORP LEGAL - LEGAL OPERATIONS",
    "CORP LEGAL-CTL, IP, & CRE",
    "Corp Security-Ho",
    "Corporate Acctg & Reporting",
    "Corporate Actuarial",
    "Corporate Audit",
    "Corporate Audit Admin",
    "Corporate Compliance",
    "Corporate Controllers-Admin.",
    "Corporate Finance Admin",
    "Corporate Finance Operations",
    "Corporate Legal",
    "Corporate Litigation",
    "Corporate Secretary",
    "Corporate Tax",
    "Creative Services",
    "Customer Experience",
    "Design",
    "Digital Marketing",
    "Employee Experience",
    "Employee Fitness Center",
    "Employee Health",
    "Employee Relations-Admin",
    "Employee Services Unit",
    "Employment Law",
    "Enterprise BI Marketing",
    "Enterprise Communications",
    "Enterprise Customer Advocacy",
    "Enterprise Customer Experience",
    "Enterprise Field Generalists",
    "Enterprise HR RVPs and Support",
    "Enterprise Innovation",
    "Enterprise Market Research",
    "Enterprise Risk Management",
    "Enterprise Talent Management",
    "Enterprise Underwriting",
    "Equity/Equity Related Invests",
    "ETM Admin",
    "Europe Innovation",
    "Event Mgmt",
    "Executive",
    "Field F&S Admin",
    "Finance & Admin",
    "Finance & Operations",
    "Financial Planning & Analysis",
    "Fixed Income Investments",
    "Global and Exec Protection",
    "Global Custody",
    "Government Relations",
    "Hr Exec Admin",
    "HR Systems Support",
    "Human Capital Analytics",
    "Innovation Executive",
    "Internal Investigations",
    "Investment Admin",
    "Investment Operations",
    "LDP - HR",
    "LDP - Shared Admin",
    "Leased Space - Field",
    "Leave of Absence",
    "Legal Shared Services",
    "Logistics-Other",
    "Marketing Services",
    "OD&I",
    "Omaha Data Center - Bldg Ops",
    "Payroll Accounting",
    "PI Communications",
    "Procurement - Operations",
    "Procurement - Sourcing",
    "Procurement - Supplier Mgmt",
    "Real Estate Equity",
    "Records & Information Mgmt",
    "Reins Analysis/Assumed Support",
    "Reinsurance",
    "Sports Sponsorship",
    "Staff Hr Support",
    "Staffing Admin",
    "Statutory Reporting",
    "Travelers Innovation Center"]],
    
    ["International", ["ACT ACTUARIAL CAD_D",
    "ACT PRICING CAD",
    "ACT R&D CAD",
    "Actuarial Europe",
    "BI Central Sales Dis",
    "BI Retail Operations",
    "BI Specialty Operations",
    "BI Underwriting",
    "Birmingham Branch",
    "Bond and Specialty Exec",
    "BSI Operations",
    "BUS INTEL CAD_D",
    "BUS STRAT PLANNING SUPPORT CAD",
    "Business Insurance Management",
    "CAD Bond Tech",
    "CAD Business Insurance Tech",
    "CAD PI Tech CO",
    "CAD Shared Tech",
    "CAD Specialty Insurance Tech",
    "CAD Technology",
    "Canada Claim CAT Team",
    "Canada Multinational IT",
    "Claim Exec",
    "Claim Field Auto Ab CAD_D",
    "Claim Field Auto Abi CAD_D",
    "Claim Field Auto Apd CAD_D",
    "Claim Field Auto Appraisal CAD",
    "Claim Field Gl CAD_D",
    "Claim Field Operations CAD_D",
    "Claim Field Prop CAD_D",
    "CLAIM FIELD SURETY CAD_D",
    "CLAIM FIELD WARRANTY CAD_D",
    "Claim Legal",
    "Claim Prop Product CAD",
    "Claim Shared Services CAD",
    "Claim Specialty InsuranceCAD_D",
    "Claims BI",
    "Claims BIS",
    "Claims BSI",
    "Claims Exec",
    "Claims Legal",
    "Claims Management",
    "Claims TIDAC",
    "Claims VAS",
    "CLM CDN STAFF COUNSEL CAD",
    "Compliance",
    "CORP COMMS CAD_D",
    "Corporate",
    "CUO Transfer to DOM",
    "Distribution",
    "Dublin Branch",
    "Eur SPE",
    "Europe Operations Management",
    "Europe Technology Baseline",
    "Europe Technology Staff",
    "EXECUTIVE CAD_D",
    "FAC ADMINISTRATION TOR CAD",
    "Facilities Administration",
    "FIN CORP FINANCE CAD",
    "FIN FP&A CAD",
    "Financial Institutions",
    "General Counsel",
    "Glasgow Branch",
    "Global Product",
    "Global Undw Ops Production",
    "Global Undw Production",
    "Health & Safety",
    "HR",
    "HR HUMAN RESOURCES CAD_D",
    "Insurance Finance",
    "International Actuarial",
    "International Business Intelli",
    "International Executive",
    "International Finance",
    "International HR",
    "International HR Lead",
    "Intl Actuarial Support",
    "Intl Cross Border Exec",
    "Intl EDA IT",
    "Intl Exec TCI Global",
    "Ireland Executive",
    "Ireland Finance Admin",
    "IT Arch & Tech Strategy CAD_D",
    "IT CAD_D",
    "IT Development Ops CAD_D",
    "IT EMSA Application Del",
    "IT Planning & Execution CAD_D",
    "IT Production Operations CAD_D",
    "IT STRATEGIC INS PLATF DEL -D",
    "Leeds Branch",
    "Legal & Secretarial",
    "LGL LEGAL CAD_D",
    "Lloyd's CAT Modeling",
    "Lloyd's Executive",
    "Lloyd's Finance",
    "Lloyds FOS Backfill",
    "Lloyds FOS IT",
    "Lloyds FOS SPE/Consulting",
    "Lloyds UW Aviation",
    "Lloyds UW Energy",
    "Lloyds UW Retail Marine",
    "London Branch",
    "LTD Post 1/1/15 Combined CO570",
    "Management Liability",
    "Manchester Branch",
    "Marketing CAD_D",
    "Multinational Executive",
    "National Sales Dis",
    "Non Executive Directors",
    "Ops BI Select Plus_D",
    "Ops BI SPCL_D",
    "OPS BILLING CENTRE CAD_D",
    "Ops BSI_D",
    "Ops Cust Service CISS",
    "OPS LEADERS_D",
    "Ops Middle Market_D",
    "Ops National Field Ops CAD_D",
    "OPS OPER EFFECTIVENESS CAD",
    "OPS PI CUST SRVC CAD",
    "OPS PI UW CAD",
    "OPS POL CONVERSION CAD",
    "OPS POL SRVS CENTRAL OAK CAD",
    "Ops_Quality_Assurance_D",
    "PI",
    "PI Central Sales Dis",
    "Portfolio Managers",
    "Public Sector",
    "Redhill Branch",
    "Reinsurance",
    "Risk",
    "RISK CONTROL CAD_D",
    "Risk Managers Commercial",
    "Risk_Management_D",
    "Shared Finance",
    "Shared Treasury",
    "SME Existing Business",
    "SME Ireland New Business",
    "SME UK New Business",
    "Technology Product",
    "TICL Offshore",
    "TML London Market Applications",
    "TML Marketing",
    "Transport",
    "Travelers Legal",
    "UK Business Intelligence",
    "UK Insurance Executive",
    "Underwriting Control",
    "US Elmira Ops Support",
    "UW BI Commercial Accounts",
    "UW BI Construction",
    "UW BI CUO DOM STAFF CAD",
    "UW BI EXEC DOM STAFF",
    "UW BI NAT OCEAN MARINE DOM",
    "UW BI Oil&Gas DOM",
    "UW BI PASS TRANSPORT DOM",
    "UW BI Prod and Compliance Dom",
    "UW BI Product & Platform",
    "UW BI Product Management",
    "UW BI SEL FIELD CENT OAK1 CAD",
    "UW BI Select Express DOM",
    "UW BI Select Field CAD",
    "UW BI SELECT MGMT",
    "UW BI TECHNOLOGY",
    "UW COMMERCIAL SURETY CENTRAL",
    "UW PI - Property",
    "UW PI CAD",
    "UW SI",
    "UW SI FINANCIAL INSTITUTIONS",
    "UW SI PRIVATE & NON-PROFIT",
    "UW SI PROFESSIONAL LIABILITY",
    "UW SI PUBLIC COMPANY LIABILITY",
    "UW SURETY",
    "UW SURETY CENTRAL",
    "UW SURETY DEVELOPER SURETY",
    "UW SURETY EAST",
    "UW SURETY HOME WARRANTY",
    "UW SURETY TECH SERVICES",
    "UW SURETY WEST",
    "Wording and Prod Devel"]],

    ["Personal Insurance", ["3PD and COE",
    "Accounting & Controls",
    "Actuarial Reserving",
    "Admin_IM",
    "Administration",
    "Agency & Field Dev & Exp",
    "Agent Sold",
    "Analytics Platform",
    "Automation Support",
    "Business Tech Ops Rating",
    "California",
    "Canada Customer Service",
    "Comp Rater Support",
    "Compelling Offerings",
    "Customer Experience",
    "Direct Markets Admin",
    "Direct To Consumer",
    "DTC Analytics",
    "FFIC General Counsel",
    "Florida",
    "Geico",
    "GF BC-Administration",
    "Human Resources",
    "Human Resources Field",
    "IM E & S",
    "Insurance & Regulatory",
    "Intuitive Experiences",
    "IT_InsuraMatch",
    "Knoxville BC-Administration",
    "Mid-Atlantic",
    "Midwest",
    "Mountain West",
    "National Auto",
    "National Property",
    "National Specialty",
    "National Underwriting",
    "ND Rewrite Team",
    "New England",
    "Northwest",
    "Operational Effectiveness",
    "Operations Administration",
    "PI Analytics",
    "PI Cust Solutions Consultants",
    "PI Domestic Ops",
    "PI Innovation",
    "PI Learning & Development",
    "PI Ops DTC Voice Sourcing",
    "PI Ops WT Sourcing",
    "PI Product TCI",
    "PI Research",
    "PI Sourcing Operations",
    "PI Tech Compelling Offerings",
    "PI Tech Data Analytics",
    "PI Tech Expansive Engagement",
    "PI Tech Innovation",
    "PI Tech Innovation AUS",
    "PI Tech Innovation CAD",
    "PI Tech Intuitive Experiences",
    "PI Tech Modernization",
    "PI Tech Production Operations",
    "PI Tech Shared Services",
    "PI Tech Shared Services Other",
    "PI Voice Sourcing",
    "PI_INSIDE_SALES",
    "Platform Administration",
    "Platform Expansive Engagement",
    "Platform Portfolio Management",
    "Policy Service_IM",
    "Pricing Support",
    "Prod Mgmt - East",
    "Prod Mgmt - West",
    "Product Administration",
    "Production Support",
    "Regulatory & Filing",
    "Richardson BC - Administration",
    "Sales - New Jersey_IM",
    "Sales Administration",
    "Sales Phones",
    "Sales Strategy",
    "Shd Svc Ins Service Reps",
    "Shd Svc Quality Assurance",
    "Shd Svc Underwriting",
    "South Central",
    "Southern",
    "Spokane BC-Administration",
    "State Product Services",
    "Strategic Marketing Retail",
    "Travelers Sold",
    "TRV Marketplace",
    "UPNY",
    "UX",
    "Workforce_Management"]],

    ["Risk Control", ["RC Analytical Lab",
    "RC Boiler Admin & Specialist",
    "RC Boiler East",
    "RC Boiler West",
    "RC Bus Unit Liaison",
    "RC Claim Liaison",
    "RC Constr Mid Atlantic-South",
    "RC Constr NE-Metro",
    "RC Constr. Central",
    "RC Constr. South Central",
    "RC Constr. Technical",
    "RC Constr. West",
    "RC Construction Defect",
    "RC Data and Analytics",
    "RC Field Central",
    "RC Field North Central",
    "RC Field Northeast",
    "RC Field Southeast",
    "RC Field West",
    "RC Forensics Specialist",
    "RC HO Operations",
    "RC Human Factors & Ergonomics",
    "RC Industrial Hygiene",
    "RC Inside",
    "RC Instrument Lab",
    "RC Marine",
    "RC Natl Accts Central",
    "RC Natl Accts Northeast",
    "RC Natl Accts Southern",
    "RC Natl Accts West",
    "RC Products Safety",
    "RC Property East",
    "RC Property Specialist",
    "RC Property West",
    "RC Sr. Management",
    "RC Training Groups",
    "RC Transportation"]],

    ["Technology and Operations", ["3rd Party",
    "AA Engineering Labor",
    "AA Platform Support",
    "Access ID Profile & Preference",
    "Account Resolution - BI",
    "Advanced Technologies",
    "Agency Admin Controls & Tech",
    "Agency Admin Prod Leadership",
    "Agency Admin Sourcing",
    "Agency Administration",
    "Agency Bill - BI",
    "Agency Bill Sourcing",
    "Agency Data",
    "Agency Help Desk",
    "Agency Lifecycle Mgmt",
    "Agency Solutions Center CIT",
    "Agency Solutions Center SIT",
    "Agile Delivery Practices",
    "Agribusiness U/W Support",
    "AI Engineering Labor",
    "Analytics",
    "Analytics Data Products",
    "API Platform",
    "Application Delivery",
    "Application Services",
    "Architecture Modernization",
    "Artificial Intelligence",
    "BC Ops Mgmt",
    "BI CRM",
    "BI Cust Solutions Consultants",
    "BI Data Modernization",
    "BI IC Agency Program Mgr",
    "BI IC Counseling",
    "BI Ops CS&S Sourcing",
    "BI Ops Execution Team",
    "BI Ops Learning",
    "BI Ops OLDPs",
    "BI Ops Quality",
    "BI Strategic Enblmnt & Prfm",
    "BI Tech Currency Management",
    "BI Tech MSA",
    "BI Technology Architecture",
    "BI Voice Sourcing",
    "Billing & Pmts Transform - Ops",
    "Billing Ops Effectiveness",
    "Billing Services - BI & PI",
    "BISO and RM",
    "Boiler Field OAS",
    "Broadcast and AV Services",
    "BSI CRM",
    "BSI Technology Architecture",
    "Bus Center Ops CA",
    "Bus Center Ops CNS",
    "Bus Center Ops Excess",
    "Bus Center Ops Inland",
    "Bus Center Ops Oil & Gas",
    "Bus Center Ops Tech",
    "Bus Relationship Mgmt_Currency",
    "Business Insights",
    "Business Intelligence Enableme",
    "CA Field OAS",
    "CA New Business OAS",
    "Canada Cyber Security",
    "Canada Digital Strat Plan Prog",
    "Canada Enterprise Tech Arch",
    "CAT Technology",
    "Change & Release Management",
    "Claim Technology Architecture",
    "Cloud Core Engineering",
    "CNS New Business OAS",
    "Connected Experience",
    "Const Field OAS",
    "Content & Collaboration",
    "Content Management Svcs",
    "Controller",
    "Core Technologies",
    "Corp Functions Data&Analytics",
    "Corp Risk & Audit",
    "Corp Tech Delivery Practices",
    "Corp Tech Engineering Accelrtn",
    "Corp Tech Management",
    "Corp Tech Management Ops",
    "Corp Tech PBT",
    "Corp Tech Prod EMSA",
    "Corp Tech QA",
    "Corporate Financial Systems",
    "Corporate Legal Technology",
    "Corporate Services Technology",
    "Corporate Tech Architecture",
    "Corporate Tools",
    "CRM Shared Services",
    "Cross Product",
    "Customer Account Operations",
    "Cyber Management Center UK",
    "Cyber_Security",
    "Cybersecurity Architecture",
    "Data Admin - Billable",
    "Data Admin - Non Billable",
    "Data and Cloud",
    "Data Engineering Labor",
    "Data Mgmt and Governance",
    "DC 2nd & 3rd shift Finishing",
    "DE Architecture",
    "Design Engineering",
    "Desktop Services - Field",
    "Desktop Services - Hartford",
    "Desktop Services - St. Paul",
    "Development IDEs and Services",
    "Digital Content Capabilities",
    "Digital Foundation & Brand Exp",
    "Digital Strat, Plan & Prog",
    "Digital Workspace",
    "Direct Bill - BI",
    "Discover Re SMG Operations",
    "Document Management",
    "Document Management Leadership",
    "Document Mgmt Sourcing",
    "Domestic Ops Leadership",
    "ED&A SPT",
    "ED&A Technology Architecture",
    "Emerging Tech",
    "Engagement Solutions",
    "Engineering Excellence",
    "Enterprise Architecture Exec",
    "Enterprise Learning Technology",
    "Enterprise Monitoring",
    "Enterprise Ops Effectiveness",
    "Entrp Framewrks and Components",
    "Event Platform",
    "Excess Casualty Field OAS",
    "Executive Support",
    "Experience Design",
    "Experience Enablement",
    "Finance Apps, Data & Analytics",
    "Financial Control Sourcing",
    "FinOps Engineering",
    "Foundational Data Products",
    "GC Billing",
    "Geospatial",
    "Global Sourcing Resources",
    "GOS&D SLT & Support",
    "GTS Europe",
    "GTS Path ITLDP",
    "Hardware Management",
    "Hartford Print",
    "HR Technology",
    "Human Resources",
    "ICS & Cybersecurity Finance",
    "ICS Analytics & Reporting",
    "ICS Leadership",
    "ICS Technology Architecture",
    "Identity & Access Mngmnt",
    "Implementation Eng",
    "Inbound Phone Team",
    "InfoDelivery Engineering Labor",
    "Infra & Installation Svcs",
    "Infra Delivery",
    "Infra User Experience",
    "Infrastructure Asset Mgmt",
    "Inland Marine Field OAS",
    "Innovation Tech",
    "Integration Services",
    "Intelligent Automation",
    "Interaction Center Leaders",
    "Internal Resolution Team",
    "IT Infrastructure CAD GTS_D",
    "Journey Post-sale",
    "Journey Pre-sale",
    "Knowledge Exchange Sharepoint",
    "Large Leadership & Support",
    "Learning",
    "Lexington Ave. NY Mailroom",
    "Loss Sensitive Billing",
    "Loss Sensitive Domestic Ops",
    "Ls Rec Mgmt Global Out-Source",
    "LSRM - NA",
    "Mail Presort",
    "Managed Container Services",
    "Management and Operations",
    "Market Consolidation",
    "Messaging",
    "MF Operating Systems",
    "MF Storage",
    "Middle Market LS OAS",
    "MM Endorsement Referrals",
    "MM Ops Field Leaders & Support",
    "MM/SC/SP Domestic Ops",
    "Mobility",
    "Multi-Function Devices",
    "National LS OAS",
    "Nat'L Prop U/Wing Support",
    "Northfield Ops OAS",
    "Northland Ops OAS",
    "Nrthlnd/Nrthfld Domestic Ops",
    "Ocean Marine Field OAS",
    "Oil & Gas Field OAS",
    "Omni",
    "Open Sys Storage",
    "PA Leadership & Support",
    "Packaging/Deployment",
    "Performance Engineering",
    "PI CRM",
    "PI D&A Initiatives",
    "PI Technology Architecture",
    "Platform",
    "Platform and App Resiliency",
    "Prem Audit-Support Services",
    "Premium Audit",
    "Premium Audit Field",
    "Premium Audit Sourcing",
    "Print and Data Operations",
    "Printing Operations",
    "Process Excellence Team",
    "Product",
    "Production",
    "Public Sector Field OAS",
    "Regional Controllers - BI",
    "Reinsurance Technology",
    "Remittance Sourcing",
    "Renewal Points",
    "RMD Operations",
    "SC & BI BC Leaders & Support",
    "SC Ops Leadership & Support",
    "Security Engineering",
    "Select Fld Ops Reg Directors",
    "Select Fld Support-OAS",
    "Select National Sales Center",
    "Servers",
    "Service Management",
    "Shared Infra & JEE Eng & Supp",
    "Small Commercial Ops BPO",
    "Source Code Management",
    "Sourcing & Supplier Mgmt Admin",
    "Sourcing Ops L&S",
    "Special Processing",
    "Strategic Execution L&S",
    "Strategic Sourcing",
    "Strategy & Transformation",
    "Tech & Ops Executive",
    "Tech Bus Support Audit, Billing",
    "Tech Bus Support RQI",
    "Tech Field OAS",
    "Technology Enablement",
    "Technology Financial Mgmt",
    "Technology Learning",
    "Technology Service Center",
    "Total Operations Sourcing",
    "Transaction Processing",
    "Treasury, Investments, ERM",
    "Voice & Contact Center Tech",
    "Voice Network"]]
]

module.exports = {departments}